### ISSUE TITLE
"files" not bundled with scripts

### ISSUE THREAD

**Issue by leidegre** [tessin/cloud-pad#17]
Investigate and find root cause for this. The code is there but something may be awry with the deployment.

**Comment by nielsbosma** [comment]
Any progress on this? :) Would be great if we could fix this.

**Comment by leidegre** [comment]
We could use Mono.Cecil to perform some rudimentary static code analysis and for all calls to System.IO.File that reads a file in some manner where we can statically determine the filename we will embed that file in the deployment package in some manner and possibly rewrite the function call in such a way that you will always get the same file back that you had at the moment of deployment.

**Comment by leidegre** [comment]
There's also a secondary option which is to use a `FileDependency` utility class and allow static init work to be done as part of packaging the script for deployment. It would look like this.

```
FileDependency myFile = FileDependency.Create("../path" + MagicExpression + "/../more-path")

Task Main(string[] args) => Program.MainAsync(this, args);

[HttpTrigger(Route = "test")]
HttpResponseMessage TestHttp(HttpRequestMessage req)
{
	var res = req.CreateResponse();
	res.Content = new StreamContent(myFile.OpenRead());
	return res;
}
```

The reason why this might be desirable is that we can force this to happen during a pre-compilation step by simply creating a new instance of the `UserQuery` class that LINQPad generates. It will also allow any type of code to be used to generate the path and we can check that the path actually resolve to a valid file.

We could also add stuff like

```
DirDependency myDir = DirDependency.Create("../path" + MagicExpression + "/../more-path")

myDir.EnumerateFiles("*")...
```

If you wanted to package an entire directory. At the very least we could emit a warning if the directory is empty. An error if the directory does not exist.

**Comment by leidegre** [comment]
This is now fixed with the new `FileDependency` class. See updated README.md for more information.
