### ISSUE TITLE
Support optional routes

### ISSUE THREAD

**Issue by nielsbosma** [tessin/cloud-pad#18]
[HttpTrigger(AuthorizationLevel.Anonymous, Route = "download/{clientkey?}")]

Getting

The route template cannot start with a '/' or '~' character and it cannot contain a '?' character.Parameter name: routeTemplate

**Comment by leidegre** [comment]
**For optional parameters you should be using query string parameters.**



Unfortunately, this is a limitation in the Azure Function Runtime, as you don't really have control over routing. You can only map simper paths to functions.

There's something called Function Proxies which would give you more control over the URL https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies but I don't think it is possible to have traditional MVC routing work all the way. It's similar but not the same (nor as flexible).

**Comment by nielsbosma** [comment]
OK, I managed to solve it without optional routing.
