### ISSUE TITLE
Add support for storage queue trigger binding

### ISSUE THREAD

**Issue by nielsbosma** [tessin/cloud-pad#9]

**Comment by leidegre** [comment]
Straight forward:

- Add metadata for queue binding
- Add funciton.json type for queue binding
- Add Funciton App prototype for queue binding

Need to experiment a bit with how the Azure Storage SDK types are bound.

- An object serializable as JSON
- string
- byte[]
- CloudQueueMessage

see https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#trigger---example

**Comment by leidegre** [comment]
Fixed via 2.0 release https://github.com/tessin/cloud-pad/releases/tag/2.0.0
